format = """
[╭](fg:overlay)\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n\
$character \
"""

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[character]
format = "[╰─$symbol](fg:overlay)"
success_symbol = '[](fg:white)'
error_symbol = '[](fg:love)'

[directory]
format = "[](fg:rose)[](fg:overlay bg:rose)[](fg:rose bg:overlay)[ $path]($style)[](fg:overlay)[─](fg:overlay)"
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[fill]
style = "fg:overlay"
symbol = "─"

[git_branch]
format = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)[ $branch ]($style)"
style = "bg:overlay fg:foam"

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '([$all_status$ahead_behind]($style))[](fg:overlay)[─](fg:overlay)'
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[time]
disabled = false
format = "[](fg:foam)[󰴈](fg:overlay bg:foam)[](fg:foam bg:overlay)[ $time]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%H:%M"

[username]
disabled = false
format = "[](fg:foam)[󰧱](fg:overlay bg:foam)[](fg:foam bg:overlay)[ $user]($style)[](fg:overlay)[─](fg:overlay)"
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

# Languages

[c]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[elixir]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[elm]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[golang]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[haskell]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[java]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[julia]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[nodejs]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[󰎙](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[nim]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[󰆥](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[rust]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[scala]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = "[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)"

[python]
style = "bg:overlay fg:pine"
format = "$symbol[ $version]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = '[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)'

[conda]
style = "bg:overlay fg:pine"
format = "$symbol[$environment]($style)[](fg:overlay)[─](fg:overlay)"
disabled = false
symbol = '[](fg:iris)[](fg:overlay bg:iris)[](fg:iris bg:overlay)'
